import React, { useState } from "react";
import { Link, useHistory } from "react-router-dom";
import "./privacyPolicy.css";

const PrivacyPolicy = (props) => {
  const [isModal] = useState(true);

  let history = useHistory();

  return (
    <div
      role="button"
      className="modal-wrapper"
      onClick={() => history.goBack()}
    >
      <div className="privacy-policy">
        <div id="privacy-policy-head" onClick={(e) => e.stopPropagation()}>
          <div id="privacy-policy-title">
            <h2>Privacy Policy</h2>
          </div>
          <div id="privacy-policy-close" onClick={() => history.goBack()}>
            Close
          </div>
        </div>

        <div id="privacy-policy-body" onClick={(e) => e.stopPropagation()}>
          <p>
            This website is a non-profit personal project. As such, the data
            collection is kept to the bare minimum needed to ensure a smooth
            experience and support technical considerations on the delivery of
            the website itself. No data is sold to third parties, however, this
            website uses third-party services which collect, store, and process
            data, as explained in the following section.
          </p>

          <h3>Cookies</h3>
          <p>
            This website uses Google Analytics, a web analysis service of Google
            Inc. (“Google”). Google Analytics uses “cookies”, text files, which
            are stored on your computer and enable analysis of the use you make
            of the website. The Google tracking codes of this website use the
            “_anonymizeIp()” function. As a result, all IP address are
            anonimized to exclude a direct personal reference before their
            storage on Google's servers. On behalf of the operator of this
            website, Google uses this information to evaluate your use of this
            website, create reports about the website activities and provide
            other services connected with the use of the website and Internet
            for the website operator. The IP address transmitted from your
            browser within the context of Google Analytics will not be
            associated with other data of Google. You can prevent storing of
            cookies on your computer via a corresponding setting of your browser
            software. You can also prevent the recording of data generated by a
            cookie with respect to your use of the website (incl. IP address) by
            Google as well as the processing of such data by Google by
            downloading and installing the browser plugin available via the
            following link: http://tools.google.com/dlpage/gaoptout?hl=en.
          </p>

          <h3>Get in touch</h3>
          <p>
            If you have any questions or concerns, you can get in touch at the
            contact details that you'll find in my github page. Please specify
            the URL of the website in your request
          </p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
